myproject/cook_site/urls.py
from django.urls import path
from cook_site import views
# from .views import all_clients, orders_by_client, order_full, upload_images, upload_images1
from .views import all_clients

from . import views




# edit_good,

app_name = 'cook_site'

urlpatterns = [
    path('', all_clients, name="all_clients"),
    path('main/', views.main, name='main'),
    path('recipes/', views.get_recipes, name='recipes'),
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('register/', views.sign_up, name='register'),

    # path('goods/', views.get_goods, name='goods'),
    # path('orders/', views.get_orders, name='orders'),
    # path('client_orders/<int:client_id>', views.get_orders_by_client_id, name='client_orders'),
    # path('delete_client/<int:client_id>', views.delete_client, name='delete_client'),
    # path('delete_goods/<int:goods_id>', views.delete_goods, name='delete_goods'),
    # path('delete_order/<int:order_id>', views.delete_order, name='delete_order'),
    # path('edit_order_goods_id/<int:order_id>/<int:goods_id>', views.edit_order_goods_id, name='edit_order_goods_id'),
    # path('client_goods/', views.client_goods, name='client_goods'),
    # path("edit/", views.get_edit_good, name="get_edit_good"),
    # path("order/<int:order_pk>", order_full, name="order_full"),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.decorators.cache import cache_page



from cook_site.views import registration

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cook_site.urls')),
    path('user/registration/', registration)
]

myproject/templates/base.html
<{% load static %}>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Сайт рецептов
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="../static/css/styles.css">
    {% endblock %}
</head>
<body>
<header class="header">
    {% block header %}

        <div class="navbar">
            <nav class="nav">
                {% now "l d M Y" %}
                {% include 'inc_menu.html' %}
            </nav>
        </div>

    {% endblock %}
</header>
<div class="main container">
{% block h1 %}
    <h1>Главная страница</h1>
{% endblock h1 %}

    {% block main %}


        <h2>Добро пожаловать на сайт рецептов</h2>


    {% endblock %}
</div>
<footer class="footer">
    {% block footer %}

        <small>
            <address>
                <a href="mailto:admin5588@mail.ru">admin5588@mail.ru</a>
                <a href="tel:749578566321">+749578566321</a>
            </address>
            &copy; TiVi_ov
            {% now "Y" %}
        </small>

    {% endblock %}
</footer>
</body>
</html>






  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/app.js' %}" defer></script>
    <title>My Site</title>
  </head>
  <body>
  	<header>
  		{%if request.user.is_authenticated %}
  			<span>Hi {{ request.user.username | title }}</span>
  			<a href="{% url 'logout' %}">Logout</a>

  		{%endif%}
  	</header>
  	<main>
	  	{% if messages %}
			<div class="messages">
			{% for message in messages %}
				<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
					{{ message }}
				</div>
			{% endfor %}
			</div>
		{% endif %}

	    {%block content%}
	    {%endblock content%}
  	</main>

  </body>
</html>

myproject/templates/inc_menu.html
{% with request.resolver_match.url_name as url_name %}
    <ul>
        <li><a href="{% url 'cook_site:login' %}" class="{% if url_name == 'login' %}active{% endif %}">
            Вход
        </a></li>
        <li><a href="{% url 'cook_site:register' %}" class="{% if url_name == 'register' %}active{% endif %}">
            Регистрация пользователя
        </a></li>




        <li><a href="{% url 'cook_site:recipes' %}" class="{% if url_name == 'recipes' %}active{% endif %}">
            Рецепты
        </a></li>

    </ul>
{% endwith %}

myproject/templates/signup.html
<h2>Регистрация</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>